### PR TITLE
♻️ Adjust zoom out

### PR DESCRIPTION
**Pull request by LeoSilvaGomes**
## Motivation

Think in the user interaction and in the user history of the flow map, was decided to refactor the way the user zoom out on the platform, when the user click out of the layers, we decided to filter this zoom out.

## Changes

- Remove click out of layer from district hook
- Add click out of layer on `Map` component
- Adjust click out of layer
- Create fit bounds for state and district
- Create `resetDistrictValues`

## Testing

- Run the application on branch `refactor/Zoom`
- Play with the map

### CODE REVIEW

**Review by enzoggqs — APPROVED** [review]
Very nice!!

**Review by valdersonjr — COMMENTED** [review]
When we get to the max zoom-in, is the only way to go back do the middle-zoom is by clicking outside the map?

**Comment by LeoSilvaGomes** [comment]
> When we get to the max zoom-in, is the only way to go back do the middle-zoom is by clicking outside the map?

Yep! But what is your proposal? Try to back to the middle-zoom by clicking on the "x" at the searchbar? 

On the other hand, we have a task to implement a back button on the header! So in that way we will have a more fluid behaviour to zoom-out on the map 

WDT?

**Comment by valdersonjr** [comment]
> > When we get to the max zoom-in, is the only way to go back do the middle-zoom is by clicking outside the map?
> 
> Yep! But what is your proposal? Try to back to the middle-zoom by clicking on the "x" at the searchbar? (It can be a good idea)
> 
> On the other hand, we have a task to implement a back button on the header! So in that way we will have a more fluid behaviour to zoom-out on the map
> 
> WDT? @valdersonjr @enzoggqs

I think you did a great job. I was just curious because when I got to the max zoom-in I had to scroll out to click outside the map. That should be solved with de back button task.

**Review by valdersonjr — APPROVED** [review]

**Pull request merged**
